---
title: 시각화의 집계(합계, 평균, 최대값 등)
description: Power BI에서 차트의 집계 변경(합계, 평균, 최대값 등)
author: mihart
manager: kfile
ms.reviewer: ''
ms.service: powerbi
ms.component: powerbi-service
ms.topic: conceptual
ms.date: 01/04/2018
ms.author: mihart
LocalizationGroup: Reports
ms.openlocfilehash: 39adfd04118362fa706f0840daa5c2520d899b5e
ms.sourcegitcommit: 80d6b45eb84243e801b60b9038b9bff77c30d5c8
ms.translationtype: HT
ms.contentlocale: ko-KR
ms.lasthandoff: 06/04/2018
ms.locfileid: "34247599"
---
# <a name="aggregates-in-power-bi-visualizations"></a>Power BI 시각화의 집계
## <a name="what-is-an-aggregate"></a>집계란?
데이터에서 값을 수학적으로 결합하려는 경우가 있습니다. 수학 연산은 합계, 평균, 최대값, 개수 등이 될 수 있습니다. 데이터의 값을 결합할 때 이를 *집계*라고 합니다. 해당 수학 연산의 결과는 *집계*입니다. 

Power BI 서비스 및 Power BI Desktop이 시각화를 만들면 데이터를 집계할 수 있습니다. 집계는 필요한 것일 뿐이지만 종종 값을 다른 방식으로 집계해야 하는 경우도 있습니다.  예를 들어, 합계와 평균을 비교하는 경우가 있습니다. 시각화에 사용되는 집계를 관리하고 변경하는 방법에는 여러 가지가 있습니다.

먼저 데이터 *유형*을 살펴보겠습니다. 왜냐하면 데이터 유형에 따라 집계할 수 있는 방법과 조건이 결정되기 때문입니다.

## <a name="types-of-data"></a>데이터 유형
대부분의 데이터 집합에는 한 가지 이상의 데이터 유형이 있습니다. 가장 기본적인 수준에서는 데이터가 숫자이거나 숫자가 아닙니다. 합계, 평균, 개수, 최소, 분산 등을 사용하여 숫자 데이터를 집계할 수 있습니다. *범주별*  데이터라고 하는 텍스트 데이터도 집계할 수 있습니다. 범주별 필드를 집계하려는 경우(**값** 또는 **도구 설명** 등 숫자 전용 버킷에 배치됨), Power BI는 각 범주의 발생 횟수를 계산하거나 각 범주의 고유 발생 횟수를 계산할 수 있습니다. 날짜와 같은 특별한 유형의 데이터에는 가장 이른 시간, 가장 늦은 시간, 처음 및 마지막 등 몇 가지 자체 집계 옵션이 있습니다. 

아래 예제에서:
- **판매 대수** 및 **제조 가격**은 숫자 데이터를 포함하는 열입니다.
-  **세그먼트**, **국가**, **제품**, **월** 및 **월 이름**은 범주별 데이터를 포함합니다.

   ![](media/service-aggregates/power-bi-aggregate-chart.png)

Power BI에서 시각화를 만들 때 숫자 필드는 일부 범주별 필드에 대해 집계됩니다(기본값은 *합계*입니다).  예를 들어, "***제품별*** 판매 대수", "***월별*** 판매 대수", "***세그먼트별*** 제조 가격" 등입니다. 일부 숫자 필드는 **측정값** 이라고 합니다. Power BI 보고서 편집기에서 측정값을 쉽게 식별할 수 있습니다. 측정값은 필드 목록에 Σ 기호로 표시됩니다. 자세한 내용은 [보고서 편집기... 둘러보기](service-the-report-editor-take-a-tour.md)를 참조하세요.

![](media/service-aggregates/power-bi-aggregate-fields.png)



## <a name="why-dont-aggregates-work-the-way-i-want-them-to"></a>내가 원하는 방식으로 작업을 집계되지 않는 이유는 무엇입니까?
Power BI 서비스에서의 집계 작업은 혼동될 수 있습니다. Power BI가 숫자 필드의 집계를 변경하지 못하게 할 수 있습니다. 또는 연도와 같은 필드를 집계하지 않고, 발생 횟수만 계산하려는 경우가 있습니다.

대부분의 경우 데이터 집합에서 필드를 정의하는 방식에 문제의 원인이 있습니다. 필드가 텍스트로 정의되어 합이나 평균을 계산할 수 없다고 할 수 있습니다. [데이터 집합 소유자만 필드를 분류하는 방식을 변경할 수 있습니다](desktop-measures.md). 따라서 데스크톱이나 데이터 집합을 만드는 데 사용된 프로그램(예 : Excel)에서 데이터 집합에 대한 소유자 권한이 있는 경우 이 문제를 해결할 수 있습니다. 그렇지 않으면 데이터 집합 소유자에게 도움을 요청해야 합니다.  

혼동을 피하는 방법은 이 문서의 끝에 **고려 사항 및 문제 해결**이라는 특별 섹션에 설명되어 있습니다.  여기에서 답을 찾을 수 없는 경우 [Power BI 커뮤니티 포럼](http://community.powerbi.com)에 질문을 게시해주시면 Power BI 팀에서 신속하게 직접 답변해드릴 것입니다.

## <a name="change-how-a-numeric-field-is-aggregated"></a>숫자 필드가 집계되는 방식 변경
다른 제품의 판매 대수의 합계를 구하는 차트가 있지만 평균값을 구하려는 경우를 가정해 보겠습니다. 

1. 범주와 측정값을 사용하는 차트를 만듭니다. 이 예에서는 제품별 판매 대수를 사용하고 있습니다.  기본적으로 Power BI는 각 제품(축 웰의 범주)에 대해 판매 대수(가치 웰의 측정값)를 합한 차트를 생성합니다.

   ![](media/service-aggregates/power-bi-aggregate-sum.png)

2. 시각화 창에서 측정값을 마우스 오른쪽 단추를 클릭하고 필요한 집계 유형을 선택합니다. 이 경우 평균을 선택하겠습니다. 필요한 집계가 표시되지 않으면 아래의 "고려 사항 및 문제 해결"을 참조하세요.  
   
   ![](media/service-aggregates/power-bi-aggregate-average.png)
   
   > [!NOTE]
   > 드롭다운 목록에서 사용할 수 있는 옵션은 1) 선택된 필드와 2) 필드가 데이터 집합 소유자별로 분류된 방식에 따라 달라집니다.
   > 
3. 시각화는 이제 평균으로 집계됩니다.

   ![](media/service-aggregates/power-bi-aggregate-average2.png)

##    <a name="ways-to-aggregate-your-data"></a>데이터를 집계하는 방법

필드 집계에 사용 가능한 일부 옵션:

* **요약 안 함**. 이 옵션을 선택할 경우 해당 필드의 각 값이 별도로 처리되고 요약되지 않습니다. 이 옵션은 일반적으로 요약하면 안 되는 숫자 ID 열이 있는 경우 사용합니다.
* **합계**. 해당 필드의 모든 값을 더합니다.
* **평균**. 값의 산술 평균을 구합니다.
* **최소값**. 가장 작은 값을 보여줍니다.
* **최대값**. 가장 큰 값을 보여줍니다.
* **개수(비어 있지 않음).** 비어 있지 않는 필드에 있는 값의 개수를 계산합니다.
* **개수(고유):** 해당 필드에서 다른 값의 개수를 계산합니다.
* **표준 편차.**
* **분산**.
* **중앙값**.  중앙값(중간값)을 표시합니다. 위와 아래에 동일한 개수의 항목이 있는 값입니다.  중앙값 두 개가 있는 경우 Power BI에서 평균을 계산합니다.

예를 들어, 이 데이터는

| 국가 | 금액 |
|:--- |:--- |
| 미국 |100 |
| 영국 |150 |
| 캐나다 |100 |
| 독일 |125 |
| 프랑스 | |
| 일본 |125 |
| 오스트레일리아 |150 |

다음 결과가 제공됩니다.

* **요약 안 함**: 각 값이 별도로 표시됩니다
* **합계**: 750
* **평균값**: 125
* **최대값**: 150
* **최소값**: 100
* **개수(비어 있지 않음):** 6
* **개수(고유):** 4
* **표준 편차:** 20.4124145...
* **분산:** 416.666...
* **중앙값:** 125

## <a name="create-an-aggregate-using-a-category-text-field"></a>범주(텍스트) 필드를 사용하여 집계 만들기
숫자가 아닌 필드도 집계할 수 있습니다. 예를 들어 제품 이름 필드가 있는 경우 이를 값으로 추가한 다음 **개수**, **고유 개수**, **첫 번째** 또는 **마지막**으로 설정할 수 있습니다. 

1. 이 예에서는 **제품** 필드를 값 웰로 끌어 왔습니다. 값 웰은 일반적으로 숫자 필드에 사용됩니다. Power BI는 텍스트 필드임을 인식하고 집계를 **요약 안 함**으로 설정하고 단일 열 테이블로 제공합니다.
   
   ![](media/service-aggregates/power-bi-aggregate-value.png)
2. 집계를 기본값인 **요약 안 함** 에서 **개수(고유)** 로 변경하는 경우 Power BI는 다른 제품의 수를 계산합니다. 이 경우 4가 있습니다.
   
   ![](media/service-aggregates/power-bi-aggregates-count.png)
3. 그리고 집계를 **개수**로 변경하면 Power BI는 총 수를 계산합니다. 이 경우에는 **제품**에 7개 항목이 있습니다. 
   
   ![](media/service-aggregates/power-bi-aggregate-count2.png)

4. 같은 필드(이 경우에는 **제품**)를 값 웰로 끌어놓고 기본 집계 **요약 안 함**을 그대로 두면 Power BI는 제품별로 계산을 세분화합니다.

   ![](media/service-aggregates/power-bi-aggregate-final.png)

## <a name="considerations-and-troubleshooting"></a>고려 사항 및 문제 해결
Q: **요약 안 함** 옵션이 없는 이유는 무엇입니까?

A: 선택한 필드는 Excel 또는 [Power BI Desktop](desktop-measures.md)에서 만든 계산된 측정값 또는 고급 측정값일 가능성이 큽니다. 각 계산된 측정값에는 하드 코딩된 고유한 수식이 있습니다. 사용 중인 집계는 변경할 수 없습니다.  예를 들어, 합계인 경우 합계만 될 수 있습니다. 필드 목록에서 계산된 측정값 은 계산기 기호로 표시됩니다.

Q: 내 필드**는** 숫자인데, **개수** 및 **고유 개수**와 같은 선택만 나타나는 이유는 무엇입니까?

A1: 데이터 집합 소유자가 실수로 또는 의도적으로 필드를 숫자로 분류*하지* 않았다고 설명할 수 있습니다. 예를 들어 데이터 집합에 **연도** 필드가 있다면 **연도** 필드는 개수를 셈하지만(즉, 1974년도에 태어난 사람의 수) 합계나 평균을 계산하지 않을 가능성이 크기 때문에 데이터 집합 소유자는 이 필드를 텍스트로 분류할 수 있습니다. 소유자는 Power BI Desktop의 데이터 집합을 열고 **모델링** 탭을 사용하여 데이터 형식을 변경할 수 있습니다.  

A2: 필드에는 계산기 아이콘이 있는 경우, 이는 *계산된 측정값*이며 각각의 계산된 측정값에는 데이터 집합 소유자만 변경할 수 있는 자체 하드 코딩된 수식이 있습니다. 사용 중인 계산은 평균이나 합계와 같은 간단한 집계일 수 있지만, "부모 범주에 대한 기여 비율"이나 "한 해 시작 이후 누계"와 같이 좀 복잡한 집계일 수도 있습니다. Power BI는 결과의 합계 또는 평균을 계산하지 않고 각 데이터 요소에 대해 하드 코딩된 수식을 사용하여 다시 계산하기만 합니다.

A3: 또 다른 원인으로는 범주별 값만 허용하는 *버킷*에 필드를 놓은 경우입니다.  이 경우 유일한 옵션은 개수 및 고유 개수입니다.

A4: 세 번째 원인은 축용 필드를 사용하는 경우입니다. 예를 들어, 가로 막대형 차트 축에서 Power BI는 각 고유 값에 하나의 막대를 표시합니다. 이 경우 필드 값을 전혀 집계하지 않습니다. 

>[!NOTE]
>이 규칙의 예외는 분산형 차트로, X 및 Y축에 대해 집계된 값이 *필요*합니다.

Q: 분산형 차트가 있고 내 필드를 집계*하지* 않고자 합니다.  어떻게 해야 합니까?

A: 필드를 X 또는 Y축 버킷이 아닌 **세부 정보** 버킷에 추가하세요.

Q: 숫자 필드를 시각화에 추가할 때 대부분의 기본값은 합계를 계산되지만 일부 기본값은 평균을 계산하거나 개수를 세거나 일부 다른 집계를 수행합니다.  기본 집계가 항상 동일하지 않는 이유는 무엇입니까?

A: 데이터 집합 소유자에게는 각 필드에 대한 기본 요약 정보를 설정하는 옵션이 있습니다. 데이터 집합 소유자인 경우 Power BI Desktop의 **모델링** 탭에서 기본 요약을 변경하세요.

Q: 저는 데이터 집합 소유자이며 필드가 집계되지 않도록 하려고 합니다.

A: Power BI Desktop의 **모델링** 탭에서 **데이터 형식**을 **텍스트**로 설정합니다.

Q: 드롭다운의 옵션으로 **요약 안 함**이 나타나지 않습니다.

A: 필드를 제거하고 다시 추가해보세요.

궁금한 점이 더 있나요? [Power BI 커뮤니티를 이용하세요.](http://community.powerbi.com/)

